import type { UnderstandingStatus } from "@/lib/ai/types";

export type MasteryLevel = "new" | "developing" | "proficient" | "mastered" | "needs-review";
export interface TopicMastery { topicId: string; topic: string; subject?: string; attempts: number; bestScore: number; latestScore: number; masteryLevel: MasteryLevel; lastAttemptAt: string; recentStatuses: UnderstandingStatus[]; }
export const topicMasteryStorageKey = "adaptivemind-topic-mastery";

export function normalizeTopicId(topic: string) { return topic.trim().toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
export function calculateMasteryLevel(attempts: number, bestScore: number, latestScore: number, recentStatuses: UnderstandingStatus[]): MasteryLevel { if (attempts === 0) return "new"; if (latestScore < 40 || recentStatuses[0] === "misconception") return "needs-review"; if (bestScore >= 85 && recentStatuses.slice(0, 2).filter((status) => status === "correct").length >= 2) return "mastered"; if (latestScore >= 70 || recentStatuses.slice(0, 2).every((status) => status === "correct" || status === "partial")) return "proficient"; return "developing"; }
export function getTopicMastery(): TopicMastery[] { try { const value: unknown = JSON.parse(localStorage.getItem(topicMasteryStorageKey) ?? "[]"); return Array.isArray(value) ? value.filter((item): item is TopicMastery => typeof item === "object" && item !== null && typeof (item as Record<string, unknown>).topicId === "string") : []; } catch { return []; } }
export function updateTopicMastery(topic: string, subject: string, score: number, status: UnderstandingStatus): TopicMastery { const all = getTopicMastery(); const topicId = normalizeTopicId(topic); const existing = all.find((item) => item.topicId === topicId); const recentStatuses = [status, ...(existing?.recentStatuses ?? [])].slice(0, 5); const entry: TopicMastery = { topicId, topic, subject, attempts: (existing?.attempts ?? 0) + 1, bestScore: Math.max(existing?.bestScore ?? 0, score), latestScore: score, masteryLevel: calculateMasteryLevel((existing?.attempts ?? 0) + 1, Math.max(existing?.bestScore ?? 0, score), score, recentStatuses), lastAttemptAt: new Date().toISOString(), recentStatuses }; localStorage.setItem(topicMasteryStorageKey, JSON.stringify([entry, ...all.filter((item) => item.topicId !== topicId)].slice(0, 50))); return entry; }
export function getMasterySummary() { const entries = getTopicMastery(); const recent = entries.slice(0, 5); return { entries, mastered: entries.filter((entry) => entry.masteryLevel === "mastered").length, developing: entries.filter((entry) => entry.masteryLevel === "developing" || entry.masteryLevel === "proficient").length, needsReview: entries.filter((entry) => entry.masteryLevel === "needs-review").length, averageRecentScore: recent.length ? Math.round(recent.reduce((sum, entry) => sum + entry.latestScore, 0) / recent.length) : null }; }
