import type { LearningDimension, LearningScores } from "@/lib/learning-dna";
import type { LessonHistoryEntry } from "@/lib/dashboard-storage";
import type { TopicMastery } from "@/lib/mastery";
import { getLessonRecommendation } from "@/lib/recommendations";

export type StudyPlanGoal = "review" | "continue" | "exam" | "habit" | "explore";
export type StudyIntensity = "light" | "balanced" | "focused";
export type StudyTaskType = "review" | "lesson" | "practice" | "understanding-check" | "reflection";
export interface StudyTask { id: string; topic: string; type: StudyTaskType; minutes: number; reason: string; teachingApproach: LearningDimension[]; completed: boolean; }
export interface StudyPlanDay { dayNumber: number; date?: string; totalMinutes: number; focus: string; tasks: StudyTask[]; }
export interface StudyPlan { id: string; createdAt: string; goal: StudyPlanGoal; durationDays: number; minutesPerDay: number; intensity: StudyIntensity; days: StudyPlanDay[]; summary: string; }
export interface StudyPlanSettings { goal: StudyPlanGoal; availableDays: number[]; minutesPerDay: number; durationDays: 3 | 7 | 14; intensity: StudyIntensity; targetDate?: string; priorities?: string; }
export const studyPlanStorageKey = "adaptivemind-study-plan";
export const studyPlanSettingsStorageKey = "adaptivemind-study-plan-settings";

export function prioritizeTopics(mastery: TopicMastery[], history: LessonHistoryEntry[]): string[] { const ranked = [...mastery].sort((a, b) => (a.masteryLevel === "needs-review" ? -2 : a.masteryLevel === "developing" ? -1 : 0) - (b.masteryLevel === "needs-review" ? -2 : b.masteryLevel === "developing" ? -1 : 0) || a.latestScore - b.latestScore).map((item) => item.topic); const recommendation = history[0] ? getLessonRecommendation(history[0].topic)?.topic : undefined; return [...new Set([...ranked, ...(recommendation ? [recommendation] : []), ...history.map((item) => item.topic), "Build consistent study habits"])].slice(0, 6); }
export function buildStudyPlanInput(scores: LearningScores, mastery: TopicMastery[], history: LessonHistoryEntry[]) { return { scores, mastery, history, topics: prioritizeTopics(mastery, history) }; }
export function allocateStudyTime(minutes: number, intensity: StudyIntensity): number[] { const base = intensity === "light" ? 2 : intensity === "focused" ? 4 : 3; const each = Math.max(5, Math.floor(minutes / base)); return Array.from({ length: base }, (_, index) => index === base - 1 ? Math.max(5, minutes - each * (base - 1)) : each); }
export function generateStudyPlan(settings: StudyPlanSettings, scores: LearningScores, mastery: TopicMastery[], history: LessonHistoryEntry[]): StudyPlan { const input = buildStudyPlanInput(scores, mastery, history); const approach = (Object.keys(scores) as LearningDimension[]).sort((a, b) => scores[b] - scores[a]).slice(0, 2); const taskTypes: StudyTaskType[] = ["review", "lesson", "practice", "understanding-check", "reflection"]; const days = Array.from({ length: settings.durationDays }, (_, index) => { const topic = input.topics[index % input.topics.length] ?? "Build consistent study habits"; const chunks = allocateStudyTime(settings.minutesPerDay, settings.intensity); const tasks = chunks.map((minutes, taskIndex) => ({ id: `task-${index + 1}-${taskIndex + 1}`, topic, type: taskTypes[(index + taskIndex) % taskTypes.length], minutes, reason: `${taskIndex === 0 ? "Focus" : "Reinforce"} this using ${approach.join(" and ")} because these are currently strong learning preferences.`, teachingApproach: approach, completed: false })); return { dayNumber: index + 1, date: new Date(Date.now() + index * 86400000).toISOString(), totalMinutes: tasks.reduce((sum, task) => sum + task.minutes, 0), focus: topic, tasks }; }); return { id: `plan-${Date.now()}`, createdAt: new Date().toISOString(), goal: settings.goal, durationDays: settings.durationDays, minutesPerDay: settings.minutesPerDay, intensity: settings.intensity, days, summary: input.history.length ? "This plan prioritizes current review needs and your next learning step." : "This starter plan is based mainly on your selected goal and current Learning DNA preferences." }; }
export function calculatePlanSummary(plan: StudyPlan) { const tasks = plan.days.flatMap((day) => day.tasks); const completed = tasks.filter((task) => task.completed); return { totalTasks: tasks.length, completedTasks: completed.length, totalMinutes: tasks.reduce((sum, task) => sum + task.minutes, 0), completedMinutes: completed.reduce((sum, task) => sum + task.minutes, 0), percentage: tasks.length ? Math.round(completed.length / tasks.length * 100) : 0, currentDay: plan.days.find((day) => day.tasks.some((task) => !task.completed))?.dayNumber ?? plan.durationDays }; }
export function validateStudyPlan(plan: StudyPlan): boolean { return plan.days.length === plan.durationDays && plan.minutesPerDay >= 5 && plan.days.every((day) => day.totalMinutes <= plan.minutesPerDay && day.tasks.every((task) => task.minutes > 0)); }
export function readStudyPlan(): StudyPlan | null { try { const value: unknown = JSON.parse(localStorage.getItem(studyPlanStorageKey) ?? "null"); return typeof value === "object" && value !== null && validateStudyPlan(value as StudyPlan) ? value as StudyPlan : null; } catch { return null; } }
export function saveStudyPlan(plan: StudyPlan) { localStorage.setItem(studyPlanStorageKey, JSON.stringify(plan)); }
